apiVersion: v1
kind: Secret
metadata:
  name: rhsensoerp-secrets
type: Opaque
data:
  connection-string: U2VydmVyPXNxbHNlcnZlcjtEYXRhYmFzZT1SaFNlbnNvRVJQREI7VXNlciBJZD1zYTtQYXNzd29yZD1Zb3VyU3Ryb25nQFBhc3N3MHJkO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9VHJ1ZTs=
